config/routes.rb
MuseumApp::Application.routes.draw do
  root "home#index"
  get "paintings", to: 'paintings#index'
  get "artists", to: 'artists#index'
  get "museums", to: 'museums#index'
  resource :paintings

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :paintings
end

app/models/museum.rb
class Museum < ActiveRecord::Base
  has_many :paintings
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  belongs_to :museum
  belongs_to :artist

  def self.search_for(query)
    where('title LIKE :query', query: "%#{query}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists=Artist.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  def index
    @museums = Museum.all
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @paintings = params[:q] ? Painting.search_for(params[:q]) : Painting.all
  end

  def new
    @painting = Painting.new
    @artists = Artist.all
    @museums = Museum.all
  end

  def create
    safe_painting_params = params.require( :painting).permit(:artist, :title, :museum, :description, :image)
    @painting = Painting.new safe_painting_params

    if @painting.save
      redirect_to @paintings
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/artists/index.html.erb
<h1>View paintings by artist!!!</h1>

<div>
  <% @artists.each do |artist| %>
    <h2 style="color: red">"<%= artist.name %>"</h2>

    <% artist.paintings.each do |painting| %>
      <p style="color: blue"><%= painting.title %></p>
      <p style="color: purple"><%= painting.museum.name %></p>
      <p><%= painting.description %></p>


      <% end %>
  <% end %>


</div>

app/views/home/index.html.erb
<h1>Welcome to Museum App!</h1>
<h2>Find Your Favorite Paintings Here</h2>

<%= form_tag 'paintings', method: :get do %>
  <%= search_field_tag :q, params[:q] %>
  <%= submit_tag "Search" %>
<% end %>

<div><%= link_to "Paintings", "paintings" %></div>
<div><%= link_to "Paintings by artist", "artists"%></div>
<div><%= link_to "Paintings by museum", "museums"%></div>

<div><%= link_to "Add New Painting", new_paintings_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MuseumApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/museums/index.html.erb
<h1>View paintings by museum!!</h1>

<div>
  <% @museums.each do |museum| %>
    <h2 style="color: red">"<%= museum.name %>"</h2>

    <% museum.paintings.each do |painting| %>
      <p style="color: blue"><%= painting.title %></p>
      <p style="color: purple"><%= painting.artist.name %></p>
      <p><%= painting.description %></p>


      <% end %>
  <% end %>


</div>

app/views/paintings/index.html.erb
<h1>Here are a list of Paintings</h1>
<div>
  <% @paintings.each do |painting| %>
    <h2>"<%= painting.title %>"</h2>
    <p><%= painting.artist.name %></p>
    <p><%= painting.museum.name %></p>
    <p><%= painting.description %></p>
    <p><%= image_tag painting.image %></p>
  <% end %>


</div>

app/views/paintings/new.html.erb
<h1>Add a new painting</h1>
<%= form_for @painting do |f| %>
  <fieldset>
    <legend>Painting</legend>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :artist %>
      <%= select_tag "artist", options_from_collection_for_select(@artists, "id", "name") %>
    </div>
    <div>
      <%= f.label :museum %>
      <%= select_tag "museum", options_from_collection_for_select(@museums, "id", "name") %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
    <div>
      <%= f.label :image %>
      <%= f.text_field :image %>
    </div>
  </fieldset>
  <%= f.submit %>
<% end %>